export const pangkat = [
  "Jenderal",
  "Letnan Jenderal",
  "Mayor Jenderal",
  "Brigadir Jenderal",
  "Kolonel",
  "Letnan Kolonel",
  "Mayor",
  "Kapten",
  "Letnan Satu",
  "Letnan Dua",
  "Pembantu Letnan Satu",
  "Pembantu Letnan Dua",
  "Sersan Mayor",
  "Sersan Kepala",
  "Sersan Satu",
  "Sersan Dua",
  "Kopral Kepala",
  "Kopral Satu",
  "Kopral Dua",
  "Prajurit Kepala",
  "Prajurit Satu",
  "Prajurit Dua",
];
